### ISSUE TITLE
Can not build project with 10.0.16922.0

### ISSUE THREAD

**Issue by timmsch** [jaurenq/XPNet#2]
I have retarget the solution to 10.0.16922.0. Unfortunately I get an error saying "cannot open source file ivalidator.h", the same appears for gchost.h.
I seem to miss something here, obviously. Any help would be appreciated.

**Comment by jaurenq** [comment]
It looks like those two files are part of the .NET SDK.  For me, they're here:

C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.2\Include\um

Even though XPNet builds against .NET Core, the C++ CLR host uses the "traditional" hosting API (ICLRRuntimeHost2).  I bet xpnet thus requires the .NET SDK to still be installed because of that.  I haven't tried building it on any machine where I wouldn't have also had the .NET SDK installed.

The coreclr team have written a new hosting API that is "Unix-friendly", to replace ICLRRuntimeHost2.  It wasn't far enough along yet for me to use when I started this project, but maybe it's to the point where we can try using it now.  That would probably resolve this issue.  In the meantime, try installing the .NET 4.6.2 SDK and let me know if that fixes the problem for you.  Thanks.

**Comment by jaurenq** [comment]
I tried swapping from the old mscoree host API to the new Unix-style one today and it seems to be working fine.  Update to the latest in master and those dependencies on ivalidator.h and gchost.h should be gone now.  Please let me know how it goes!

**Comment by timmsch** [comment]
It compiles thanks!
