### ISSUE TITLE
Build settings

### ISSUE THREAD

**Issue by jarrodb291** [jaurenq/XPNet#7]
I was able to get the project to build properly, and have the plugin load successfully into X-Plane.  Then something changed (I don't know what) and I can't get the plugin to work anymore.

I've noticed that there is an odd file in the build folder (see picture).  XPNet.LoggerPlugin.dll has an older modified date than all the others.  Even when I delete the whole folder and force a full rebuild, this file does not show the current date/time as when it was modified.

When I got this to work previously I remember changing the start project setting until this file showed as being updated just now.  For some reason, I can't make this happen again.

Am I missing something here about the project configuration?

![image](https://user-images.githubusercontent.com/6101481/40465303-ee306720-5ed4-11e8-9caa-c470602d6330.png)

**Comment by jaurenq** [comment]
Right-click on the LoggerPlugin project in Visual Studio and select build, then go look for the updated XPNet.LoggerPlugin.dll in the output folder for _that project_.  It looks from the picture you posted like you're looking in the top-level output folder, and I'm actually not sure why the LoggerPlugin _ever_ ended up in that folder, but for sure if you look in the output folder of the LoggerPlugin project itself, you should always be able to find the newest build output.

The other possibility is that nothing actually changed to force the plugin to rebuild.  Unless you issue a Clean, VS won't rebuild a C# DLL unless you change one of the source files or dependencies that go into it.  If you haven't changed anything, then it will use the previous build output instead of building a new one.

Regarding the plugin no longer working, what shows up in the X-Plane or XPNet log files?

**Comment by jarrodb291** [comment]
I downloaded the original project again and setup the build from scratch, seems to be working fine now so not sure what the cause of this was.
